Name cannot be the file path
A side effect of the previous path being specified as a single word was that it passed without error as a name, but on changing the variable to a complete path GA produces an error stating:
Error: The artifact name is not valid: …  Contains the following character:  Forward slash /
Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n, Backslash \, Forward slash /

These characters are not allowed in the artifact name due to limitations with certain file systems such as NTFS. To maintain file system agnostic behavior, these characters are intentionally not allowed to prevent potential problems with downloads on different file systems.

In other words, the name cannot be a file path.